### ISSUE TITLE
Re-implement issue

### ISSUE THREAD

**Issue by 11abcdefghij11** [tuanct1997/Federated-Learning-ASR-based-on-wav2vec-2.0#10]
Hi, thanks for the awesome work.
However,I am facing some problems while trying to reproduce this code, I sincerely hope to get your help. Due to the limitation of hardware resources, I am using less than 24Gb GPU to complete the model training, is there any solution for this situation?

**Comment by tuanct1997** [comment]
Hi @11abcdefghij11 ,

I hope this is not too late. Since it's Wav2Vec2 model, to my best of knowledge, currently we have no way to do it on less than 24GB GPU while training. It could work for testing phase but not training. 

But if you find a way to do it, I would really happy if you could share it with me. Thank you and have a nice day!

**Comment by 11abcdefghij11** [comment]
Thank you for replying me.Due to hardware resource limitations, I&nbsp; only have one 24GB GPU. Can it support the execution of this code? If not, can the code run by training clients one by one in each round? If this method is feasible, how long does it take to complete the model training? I hope you can give me some advice, thank you very much.




小玉
***@***.***


---Original---
From: ***@***.***&gt;
Date: Fri, Jul 12, 2024 22:23 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [tuanct1997/Federated-Learning-ASR-based-on-wav2vec-2.0]Re-implement issue (Issue #10)




 
Hi @11abcdefghij11 ,
 
I hope this is not too late. Since it's Wav2Vec2 model, to my best of knowledge, currently we have no way to do it on less than 24GB GPU while training. It could work for testing phase but not training.
 
But if you find a way to do it, I would really happy if you could share it with me. Thank you and have a nice day!

**Comment by tuanct1997** [comment]
I believe it could. As long as gpu meet 24GB of GPU. You will need more RAM instead. In the code, I only pump data to GPU when needed. 

It has been a long time since last training, I honestly don't remember exactly. But I think it's 3 days for me to finished 100 steps with 20 clients using 5 GPU 32GB. You could reduce the number of clients so it could be faster.

On the other hand, I highly suggested to use the codebase from Flower, I have contributed this code to Flower framework as baseline. So it should be adapted to newer version of Flower and it's also continuing maintain by Flower team 👍

**Comment by 11abcdefghij11** [comment]
Thank you so much.












小玉
***@***.***


---Original---
From: ***@***.***&gt;
Date: Fri, Jul 12, 2024 22:54 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [tuanct1997/Federated-Learning-ASR-based-on-wav2vec-2.0]Re-implement issue (Issue #10)




 
I believe it could. As long as gpu meet 24GB of GPU. You will need more RAM instead. In the code, I only pump data to GPU when needed.
 
It has been a long time since last training, I honestly don't remember exactly. But I think it's 3 days for me to finished 100 steps with 20 clients using 5 GPU 32GB. You could reduce the number of clients so it could be faster.
 
On the other hand, I highly suggested to use the codebase from Flower, I have contributed this code to Flower framework as baseline. So it should be adapted to newer version of Flower and it's also continuing maintain by Flower team 👍
